### ISSUE TITLE
профиль

### ISSUE THREAD

**Issue by miroshiiii** [Zloiben/Git#7]
это профиль ебать да

- [ ] хуй 1
- [ ] хуй 2
- [ ] хуй 4

**Comment by Zloiben** [comment]
ХУУУУУУУУУУУУУУУУУУУУУУУУУЙ

**Comment by Zloiben** [comment]
Ты пидр ты пидр ты пидр ты пидр**зшвыавщыоышоавышвавзшвышыоавхывощшавых**

**Comment by Zloiben** [comment]
ывщаоывао ывта зывоа звы азвыо азвыо звышоа ызвшо ызвшо зывоа зшыов зоыв а

**Comment by Zloiben** [comment]
ЩФЫ щтфвщфтыщфшты щфшты вфщышт ФЩЫГТВфщыт вф щшфщышв ЩШОЩФтв щшфы фщщыш тЩТФВ щытф вфы тфыщвтфыФЩЫВТ щфы щфщы вщфтЩФТВЫфщы щфщыв фыщвФЩЫВтщш тщфытвщ тфыщвфштыФЩЫШТВщшфтывщтфыщвтфщывфыщв щфтЫ ЩТФШЫвщ тфщывт фывщфтыв ЩШЫФЩвф щфыщвыфщФЩЫ вщгфывфщы щвфыщвыщшвфы щЩШФЩШ ШЩЫВЩШШЩЫВЫШВЫ щшощышо щфштывщыфвщывй
